/**
 * Barrels - turn a directory of JSX modules into one generated module.
 *
 *   barrels/blog/hello-world.jsx   →   barrels/blog.js (auto-generated)
 *
 * The generated barrel re-exports every entry as `entries` (sorted ids)
 * and `posts` (id → { component, meta }). It is a pure function of the
 * file names: entries are not evaluated at generation time, so the
 * generator has no dependency on the build pipeline and works anywhere.
 */
import { readdir, writeFile } from "node:fs/promises";
import { join, basename, relative } from "node:path";
import { isJSXFile } from "./utils.js";

/**
 * Render the barrel module source for a directory.
 * @param {string} dirName - Directory name (used in the relative import paths)
 * @param {string[]} fileNames - File names inside the directory (non-JSX files are ignored)
 * @returns {string}
 */
export function renderBarrel(dirName, fileNames) {
  const entries = fileNames
    .filter(isJSXFile)
    .map((file) => ({ id: file.replace(/\.(jsx|tsx)$/, ""), file }))
    .sort((a, b) => a.id.localeCompare(b.id));

  const imports = entries
    .map(({ file }, i) => `import * as m${i} from ${JSON.stringify(`./${dirName}/${file}`)};`)
    .join("\n");
  const ids = entries.map(({ id }) => JSON.stringify(id));
  const posts = entries
    .map(({ id }, i) => `  ${JSON.stringify(id)}: { component: m${i}.default, meta: m${i}.meta ?? null }`)
    .join(",\n");

  return `// Auto-generated barrel file - DO NOT EDIT
// Generated by Ono SSG from ${dirName}/

${imports}

export const entries = [${ids.join(", ")}];

export const posts = {
${posts}
};
`;
}

/**
 * Generate `<barrelDir>.js` next to a barrel directory.
 * @param {string} barrelDir
 * @param {{ silent?: boolean }} [options]
 * @returns {Promise<string | null>} Path of the generated file, or null if the directory has no entries
 */
export async function generateBarrel(barrelDir, options = {}) {
  const { silent = false } = options;

  /** @type {string[]} */
  let fileNames;
  try {
    fileNames = (await readdir(barrelDir, { withFileTypes: true }))
      .filter((entry) => entry.isFile())
      .map((entry) => entry.name);
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
    fileNames = [];
  }
  if (!fileNames.some(isJSXFile)) return null;

  const barrelPath = `${barrelDir}.js`;
  await writeFile(barrelPath, renderBarrel(basename(barrelDir), fileNames));

  if (!silent) {
    console.log(`  Generated: ${relative(process.cwd(), barrelPath)}`);
  }
  return barrelPath;
}

/**
 * Generate a barrel for every subdirectory of `barrelsRoot`.
 * @param {string} barrelsRoot
 * @param {{ silent?: boolean }} [options]
 * @returns {Promise<string[]>} Paths of the generated files
 */
export async function generateBarrels(barrelsRoot, options = {}) {
  const { silent = false } = options;

  let dirs;
  try {
    dirs = (await readdir(barrelsRoot, { withFileTypes: true })).filter((e) => e.isDirectory());
  } catch (error) {
    if (error.code === "ENOENT") return [];
    throw error;
  }

  const results = [];
  for (const dir of dirs) {
    const result = await generateBarrel(join(barrelsRoot, dir.name), { silent: true });
    if (result) results.push(result);
  }

  if (!silent && results.length > 0) {
    console.log(`Generated ${results.length} barrel file(s)`);
  }
  return results;
}
