/**
 * Barrel file generator for blog content
 * Automatically generates index.ts files that export all posts
 */
import { readdir, writeFile, stat } from "node:fs/promises";
import { join, basename, relative } from "node:path";
import { existsSync, watch } from "node:fs";

/**
 * Convert filename to valid JavaScript variable name
 * @param {string} filename
 * @returns {string}
 */
function toVariableName(filename) {
  // Remove extension and convert to valid identifier
  const name = basename(filename).replace(/\.(tsx?|jsx?)$/, "");
  // Replace invalid chars with underscore, ensure starts with letter
  let varName = name.replace(/[^a-zA-Z0-9]/g, "_");
  if (/^[0-9]/.test(varName)) {
    varName = "_" + varName;
  }
  return varName;
}

/**
 * Get all content files in a directory
 * @param {string} dir - Directory path
 * @returns {Promise<string[]>} Array of file paths
 */
async function getContentFiles(dir) {
  if (!existsSync(dir)) {
    return [];
  }

  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    if (entry.isFile()) {
      const ext = entry.name.match(/\.(tsx?|jsx?)$/);
      // Skip index files and non-ts/tsx/js/jsx files
      if (ext && !entry.name.startsWith("index.")) {
        files.push(entry.name);
      }
    }
  }

  return files.sort();
}

/**
 * Generate barrel file content
 * @param {string[]} files - Array of filenames
 * @returns {string} Generated TypeScript/JavaScript code
 */
function generateBarrelContent(files) {
  if (files.length === 0) {
    return `// Auto-generated by ono - no posts found
export const posts = [];
`;
  }

  const imports = files.map((file) => {
    const varName = toVariableName(file);
    const modulePath = "./" + file.replace(/\.(tsx?|jsx?)$/, "");
    return `import * as ${varName} from "${modulePath}";`;
  });

  const postsArray = files.map((file) => {
    const varName = toVariableName(file);
    return `  { meta: ${varName}.meta, Content: ${varName}.default, ...${varName} }`;
  });

  return `// Auto-generated by ono - do not edit manually
${imports.join("\n")}

export const posts = [
${postsArray.join(",\n")}
];

// Re-export individual posts for direct import
${files.map((file) => {
  const varName = toVariableName(file);
  return `export { ${varName} };`;
}).join("\n")}
`;
}

/**
 * Generate barrel file for a content directory
 * @param {string} dir - Content directory path
 * @param {Object} [options]
 * @param {boolean} [options.silent] - Suppress console output
 * @returns {Promise<string>} Path to generated barrel file
 */
export async function generateBarrelFile(dir, options = {}) {
  const { silent = false } = options;
  const files = await getContentFiles(dir);
  const content = generateBarrelContent(files);
  const barrelPath = join(dir, "index.ts");

  await writeFile(barrelPath, content, "utf-8");

  if (!silent) {
    console.log(`📦 Generated barrel file: ${barrelPath} (${files.length} posts)`);
  }

  return barrelPath;
}

/**
 * Generate barrel files for all content subdirectories
 * @param {string} contentDir - Root content directory
 * @param {Object} [options]
 * @returns {Promise<string[]>} Array of generated barrel file paths
 */
export async function generateAllBarrelFiles(contentDir, options = {}) {
  if (!existsSync(contentDir)) {
    return [];
  }

  const entries = await readdir(contentDir, { withFileTypes: true });
  const barrelFiles = [];

  for (const entry of entries) {
    if (entry.isDirectory()) {
      const subDir = join(contentDir, entry.name);
      const barrelPath = await generateBarrelFile(subDir, options);
      barrelFiles.push(barrelPath);
    }
  }

  return barrelFiles;
}

/**
 * Watch content directory and regenerate barrel files on change
 * @param {string} contentDir - Content directory to watch
 * @param {Object} [options]
 * @param {Function} [options.onGenerate] - Callback after generation
 * @returns {Function} Cleanup function to stop watching
 */
export function watchContentDir(contentDir, options = {}) {
  const { onGenerate } = options;

  if (!existsSync(contentDir)) {
    console.warn(`⚠️  Content directory not found: ${contentDir}`);
    return () => {};
  }

  const watchers = [];
  let debounceTimer = null;

  const regenerate = async (changedDir) => {
    clearTimeout(debounceTimer);
    debounceTimer = setTimeout(async () => {
      try {
        await generateBarrelFile(changedDir);
        if (onGenerate) {
          await onGenerate(changedDir);
        }
      } catch (error) {
        console.error(`Error regenerating barrel file:`, error.message);
      }
    }, 100);
  };

  // Watch each subdirectory
  const setupWatchers = async () => {
    const entries = await readdir(contentDir, { withFileTypes: true });

    for (const entry of entries) {
      if (entry.isDirectory()) {
        const subDir = join(contentDir, entry.name);
        const watcher = watch(subDir, { recursive: false }, (eventType, filename) => {
          if (filename && /\.(tsx?|jsx?)$/.test(filename) && !filename.startsWith("index.")) {
            console.log(`📝 Content changed: ${filename}`);
            regenerate(subDir);
          }
        });
        watchers.push(watcher);
      }
    }
  };

  setupWatchers().catch(console.error);

  // Return cleanup function
  return () => {
    clearTimeout(debounceTimer);
    watchers.forEach((w) => w.close());
  };
}

/**
 * Create a new post file from template
 * @param {string} contentDir - Content directory
 * @param {string} title - Post title
 * @param {Object} [options]
 * @param {string} [options.author] - Author name
 * @param {string[]} [options.tags] - Tags
 * @returns {Promise<string>} Path to created file
 */
export async function createPost(contentDir, title, options = {}) {
  const { author = "", tags = [] } = options;

  // Generate slug from title
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

  // Generate date prefix
  const date = new Date();
  const dateStr = date.toISOString().split("T")[0];
  const filename = `${dateStr}-${slug}.tsx`;
  const filepath = join(contentDir, filename);

  const tagsStr = tags.length > 0 ? `["${tags.join('", "')}"]` : "[]";

  const content = `import { Markdown } from "@hashrock/ono/blog";

export const meta = {
  slug: "${slug}",
  title: "${title}",
  date: new Date("${dateStr}"),
  author: "${author}",
  tags: ${tagsStr},
};

export default function Content() {
  return (
    <>
      <Markdown>{\`
# ${title}

Write your content here...
      \`}</Markdown>
    </>
  );
}
`;

  await writeFile(filepath, content, "utf-8");
  console.log(`✨ Created new post: ${filepath}`);

  // Regenerate barrel file
  await generateBarrelFile(contentDir);

  return filepath;
}
