// Auto-generated barrel file - DO NOT EDIT
// Generated by Ono SSG

export type Meta = {
  title: string;
  date: string;
  author: string;
  tags?: string[];
};

export { default as gettingStarted, meta as gettingStartedMeta } from './blog/getting-started.tsx';
export { default as helloWorld, meta as helloWorldMeta } from './blog/hello-world.tsx';

export const entries = ['getting-started', 'hello-world'] as const;
export type EntryId = typeof entries[number];

export const posts = {
  'getting-started': { component: gettingStarted, meta: gettingStartedMeta },
  'hello-world': { component: helloWorld, meta: helloWorldMeta }
};
